#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glance"
name = "Glance"
description.en = "Self-hosted dashboard that puts all your feeds in one place"
description.fr = "Tableau de bord auto-hébergé qui regroupe tous vos flux au même endroit"

version = "0.7.3~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://github.com/glanceapp/glance/blob/main/docs/configuration.md"
code = "https://github.com/glanceapp/glance"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract   = true
    amd64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.3/glance-linux-amd64.tar.gz"
    amd64.sha256 = "49213dbee02d10ef5eb42ee2535950cf2fe7a92b8a20ba93314037601c8440d4"
    arm64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.3/glance-linux-arm64.tar.gz"
    arm64.sha256 = "2ae8da12638aa91d2343e9633f8779838fd797c56296bb151565eca1dc466cf8"
    armhf.url = "https://github.com/glanceapp/glance/releases/download/v0.7.3/glance-linux-armv7.tar.gz"
    armhf.sha256 = "56e534e746e23ffcdeb0d39328b700d9a9fb07cd0eb125506d9e76437539478d"
    i386.url = "https://github.com/glanceapp/glance/releases/download/v0.7.3/glance-linux-386.tar.gz"
    i386.sha256 = "52dfbbb9c21ecfde9ec3932cb0dccd69e577b64f2a3dc215b25f944a021f9000"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^glance-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^glance-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^glance-linux-armv7.tar.gz$"
    autoupdate.asset.i386 = "^glance-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
