#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glance"
name = "Glance"
description.en = "Self-hosted dashboard that puts all your feeds in one place"
description.fr = "Tableau de bord auto-hébergé qui regroupe tous vos flux au même endroit"

version = "0.7.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
admindoc = "https://github.com/glanceapp/glance/blob/main/docs/configuration.md"
code = "https://github.com/glanceapp/glance"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract   = true
    amd64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.0/glance-linux-amd64.tar.gz"
    amd64.sha256 = "897d04acf31e1dd092b8d845332f573539805319d4d435beacaa1d832051e0e0"
    arm64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.0/glance-linux-arm64.tar.gz"
    arm64.sha256 = "cd29bc1a7ed6f10437b198051a56f1a8ea0e12fae3e3dc7be0a0ccc355b983a1"
    armhf.url = "https://github.com/glanceapp/glance/releases/download/v0.7.0/glance-linux-armv7.tar.gz"
    armhf.sha256 = "05188296fa074bef108727be046770eb0ac80729e25358c82ffe3429c79a46b9"
    i386.url = "https://github.com/glanceapp/glance/releases/download/v0.7.0/glance-linux-386.tar.gz"
    i386.sha256 = "254d99ee3db11a7ef90e6928060ab8d24a2113c191569e70febee6b33359c573"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^glance-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^glance-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^glance-linux-armv7.tar.gz$"
    autoupdate.asset.i386 = "^glance-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
