#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glance"
name = "Glance"
description.en = "Self-hosted dashboard that puts all your feeds in one place"
description.fr = "Tableau de bord auto-hébergé qui regroupe tous vos flux au même endroit"

version = "0.6.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
admindoc = "https://github.com/glanceapp/glance/blob/main/docs/configuration.md"
code = "https://github.com/glanceapp/glance"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract   = true
    amd64.url = "https://github.com/glanceapp/glance/releases/download/v0.6.2/glance-linux-amd64.tar.gz"
    amd64.sha256 = "54140481262258cdccd1253d486041219a74354812fabe35b6d9863efc108da0"
    arm64.url = "https://github.com/glanceapp/glance/releases/download/v0.6.2/glance-linux-arm64.tar.gz"
    arm64.sha256 = "962ae694171f7332d8821082d0f636006291ada15a3f202f9c402456397d20f2"
    armhf.url = "https://github.com/glanceapp/glance/releases/download/v0.6.2/glance-linux-armv7.tar.gz"
    armhf.sha256 = "7c2edaa735ec199689268b014de88bef20f7b4bb8789a5a6b4f3a7177bca684d"
    i386.url = "https://github.com/glanceapp/glance/releases/download/v0.6.2/glance-linux-386.tar.gz"
    i386.sha256 = "24d880f2963ddcb0c869641f27405b71e4c7c254daf69b8dcb793a38be4a7eec"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^glance-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^glance-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^glance-linux-armv7.tar.gz$"
    autoupdate.asset.i386 = "^glance-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
