#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glance"
name = "Glance"
description.en = "Self-hosted dashboard that puts all your feeds in one place"
description.fr = "Tableau de bord auto-hébergé qui regroupe tous vos flux au même endroit"

version = "0.8.6~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://github.com/glanceapp/glance/blob/main/docs/configuration.md"
code = "https://github.com/glanceapp/glance"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract   = true
    amd64.url = "https://github.com/glanceapp/glance/releases/download/v0.8.6/glance-linux-amd64.tar.gz"
    amd64.sha256 = "d27fb887eece24859f6ed3881ebb28c9d0a4fe6ae01acfa31bb39543fbf69784"
    arm64.url = "https://github.com/glanceapp/glance/releases/download/v0.8.6/glance-linux-arm64.tar.gz"
    arm64.sha256 = "8887f3ffbaa7083713ea51ed6d476d1d68d307836d43a5146fbeb8fd1fbd6513"
    armhf.url = "https://github.com/glanceapp/glance/releases/download/v0.8.6/glance-linux-armv7.tar.gz"
    armhf.sha256 = "42b2b2c6a433c2c1c3a7e93179fe0ca820731a0f6f7ea160876e467bdb4f8cc0"
    i386.url = "https://github.com/glanceapp/glance/releases/download/v0.8.6/glance-linux-386.tar.gz"
    i386.sha256 = "c03d3e51c9178562ed11875f06089be75181e8de193cd2aab615e8ce6954414f"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^glance-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^glance-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^glance-linux-armv7.tar.gz$"
    autoupdate.asset.i386 = "^glance-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
