#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "glance"
name = "Glance"
description.en = "Self-hosted dashboard that puts all your feeds in one place"
description.fr = "Tableau de bord auto-hébergé qui regroupe tous vos flux au même endroit"

version = "0.7.12~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
admindoc = "https://github.com/glanceapp/glance/blob/main/docs/configuration.md"
code = "https://github.com/glanceapp/glance"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract   = true
    amd64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.12/glance-linux-amd64.tar.gz"
    amd64.sha256 = "e740f7345a60b4a8909adf3eb4817404292be8b353bb9c58367221c250ec9d8a"
    arm64.url = "https://github.com/glanceapp/glance/releases/download/v0.7.12/glance-linux-arm64.tar.gz"
    arm64.sha256 = "50dae952c2c7849b9521f5e85018a586a48cf2f2f3025e60bc7621bab255d8a9"
    armhf.url = "https://github.com/glanceapp/glance/releases/download/v0.7.12/glance-linux-armv7.tar.gz"
    armhf.sha256 = "c0416f4b5308a9bd571314c6574bed70e243db53d59d37e55ec31efbf4590804"
    i386.url = "https://github.com/glanceapp/glance/releases/download/v0.7.12/glance-linux-386.tar.gz"
    i386.sha256 = "750dc788944d2f01329e6a5c213e9e1ec185ad31fb0d721c4b838d7c5e063051"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^glance-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^glance-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^glance-linux-armv7.tar.gz$"
    autoupdate.asset.i386 = "^glance-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
